---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: instana-agent-operator
  name: controller-manager
  namespace: instana-agent
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: instana-agent-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: instana-agent-operator
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - ppc64le
                      - s390x
                      - arm64
      containers:
        - args:
            - --leader-elect
          command:
            - /manager
          image: icr.io/instana/instana-agent-operator:2.1.10
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          name: manager
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 200m
              memory: 600Mi
            requests:
              cpu: 200m
              memory: 200Mi
          securityContext:
            allowPrivilegeEscalation: true
      serviceAccountName: instana-agent-operator
      terminationGracePeriodSeconds: 10
